/**
 *             Assignment3, COMP482
 * Class:      Authenticate.java
 * Purpose:    Verify login credentials for ABC Therapy client management software.
 *
 * @author:    David Fiske
 * Date:       July 1, 2019
 * Version     1.0
 */
package comp482a;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Create a new instance of Authenticate. This is the first part of
 * the program where the user begins. The user must provide valid 
 * credentials to proceed to MainView.java.   
 */
public class Authenticate extends javax.swing.JFrame {

    ArrayList<Employee> employees;
    ArrayList<Settings> settingsDB;

    /**
     * Creates new form Authenticate
     */
    public Authenticate() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * Load the list of employees from the file into the array.
     * 
     * Based on: 
     * 
     * Jurrius, J. [Johan Jurrius] (2017, September 18). 
     * Java GUI in Netbeans [Video file]. 
     * Retrieved June 19, 2019, from https://www.youtube.com/watch?v=GZ9MT2myBf8
     */
    public void populateStaffList() {
        // Load the list of settings from the file
        settingsDB = new ArrayList<Settings>();
        populateSettingsList();
        
        try {
            // FileInputStream file2 = new FileInputStream("Staff.dat");
            FileInputStream file2 = new FileInputStream(settingsDB.get(0).getDatabaseStaff().toString());
            ObjectInputStream inputFile2 = new ObjectInputStream(file2);
            
            boolean endOfFile = false;
            
            while (!endOfFile) {
                try {
                    employees.add((Employee)inputFile2.readObject());
                }
                catch (EOFException e) {
                    endOfFile = true;
                }
                catch (Exception f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            
            inputFile2.close();
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * Load the list of settings from the file into the array.
     * 
     * Based on: 
     * 
     * Jurrius, J. [Johan Jurrius] (2017, September 18). 
     * Java GUI in Netbeans [Video file]. 
     * Retrieved June 19, 2019, from https://www.youtube.com/watch?v=GZ9MT2myBf8
     */
    public void populateSettingsList() {
        try {
            FileInputStream file3 = new FileInputStream("Settings.dat");
            ObjectInputStream inputFile3 = new ObjectInputStream(file3);
            
            boolean endOfFile = false;
            
            while (!endOfFile) {
                try {
                    settingsDB.add((Settings)inputFile3.readObject());
                }
                catch (EOFException e) {
                    endOfFile = true;
                }
                catch (Exception f) {
                    JOptionPane.showMessageDialog(null, f.getMessage());
                }
            }
            
            inputFile3.close();
        }
        catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authenticatePanel = new javax.swing.JPanel();
        usernamePanel = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        passwordPanel = new javax.swing.JPanel();
        pwdPassword = new javax.swing.JPasswordField();
        titleLabel = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ABC Therapy");
        setPreferredSize(new java.awt.Dimension(1200, 702));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 702));

        authenticatePanel.setBackground(new java.awt.Color(204, 204, 204));
        authenticatePanel.setPreferredSize(new java.awt.Dimension(1200, 672));

        usernamePanel.setBackground(new java.awt.Color(204, 204, 204));
        usernamePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Balsamiq Sans", 1, 14))); // NOI18N
        usernamePanel.setToolTipText("");

        txtUsername.setFont(new java.awt.Font("Balsamiq Sans", 1, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(42, 120, 228));
        txtUsername.setToolTipText("");
        txtUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        txtUsername.setPreferredSize(new java.awt.Dimension(201, 27));
        txtUsername.setSelectionColor(new java.awt.Color(42, 120, 228));

        javax.swing.GroupLayout usernamePanelLayout = new javax.swing.GroupLayout(usernamePanel);
        usernamePanel.setLayout(usernamePanelLayout);
        usernamePanelLayout.setHorizontalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        usernamePanelLayout.setVerticalGroup(
            usernamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        passwordPanel.setBackground(new java.awt.Color(204, 204, 204));
        passwordPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Balsamiq Sans", 1, 14))); // NOI18N
        passwordPanel.setToolTipText("");
        passwordPanel.setMinimumSize(new java.awt.Dimension(100, 100));

        pwdPassword.setFont(new java.awt.Font("Balsamiq Sans", 1, 14)); // NOI18N
        pwdPassword.setForeground(new java.awt.Color(42, 120, 228));
        pwdPassword.setToolTipText("");
        pwdPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        pwdPassword.setPreferredSize(new java.awt.Dimension(201, 27));
        pwdPassword.setSelectionColor(new java.awt.Color(42, 120, 228));

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        titleLabel.setFont(new java.awt.Font("Balsamiq Sans", 1, 40)); // NOI18N
        titleLabel.setText("ABC Therapy");
        titleLabel.setPreferredSize(new java.awt.Dimension(745, 48));

        btnLogIn.setBackground(new java.awt.Color(255, 255, 255));
        btnLogIn.setFont(new java.awt.Font("Balsamiq Sans", 1, 16)); // NOI18N
        btnLogIn.setText("Log In");
        btnLogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        btnLogIn.setMaximumSize(new java.awt.Dimension(100, 48));
        btnLogIn.setMinimumSize(new java.awt.Dimension(100, 48));
        btnLogIn.setPreferredSize(new java.awt.Dimension(100, 48));
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout authenticatePanelLayout = new javax.swing.GroupLayout(authenticatePanel);
        authenticatePanel.setLayout(authenticatePanelLayout);
        authenticatePanelLayout.setHorizontalGroup(
            authenticatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenticatePanelLayout.createSequentialGroup()
                .addGroup(authenticatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(authenticatePanelLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(authenticatePanelLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        authenticatePanelLayout.setVerticalGroup(
            authenticatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenticatePanelLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addGroup(authenticatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(authenticatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(authenticatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(authenticatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("User Login");
        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // Load the list of employees from the file
        employees = new ArrayList<Employee>();
        populateStaffList();
        
        // Check for valid logins
        String loginUsername = txtUsername.getText();
        String loginPassword = new String (pwdPassword.getPassword());
        boolean logInCheck = false; 
        for (int i = 0; i < employees.size(); i++) {
            if (
                Objects.equals(loginUsername, employees.get(i).getUsername()) &&
                Objects.equals(loginPassword, employees.get(i).getPassword()) &&
                // Make sure the employee is still active
                Objects.equals(employees.get(i).getStatusText(), "Active")  
               ){
                    // Open the ABC Therapy Main Program Window
                    MainView objectMainView = new MainView();
                    // Change the home page user label to the employee name
                    objectMainView.setHomeTitleLabel(employees.get(i).getFirstName().toString() + " " + employees.get(i).getLastName().toString());
                    // Close the Authenticate Window
                    logInCheck = true;
                    dispose();
                    break;
                // Administrator mode incase there are no available login accounts
            }   else if (loginUsername.equals("admin") && loginPassword.equals("password")) {
                    // Open the ABC Therapy Main Program Window
                    MainView objectMainView = new MainView();
                    // Change the home page user label
                    objectMainView.setHomeTitleLabel("Administrator");
                    // Close the Authenticate Window
                    logInCheck = true;
                    dispose();
                    break;
                // Fail to authenticate
            }   else {
                    logInCheck = false;
                }
        }
        // Error Message for Incorrect Login or Password
        if (logInCheck == false) {
        JOptionPane.showMessageDialog(this, "Please enter a valid username and password.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authenticate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authenticate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authenticate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authenticate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authenticate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel authenticatePanel;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPanel usernamePanel;
    // End of variables declaration//GEN-END:variables
}
